FROM node:18 AS build
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
 
FROM build AS copy
WORKDIR /usr/src/app
COPY --from=build /usr/src/app .

 
FROM copy AS base
WORKDIR /usr/src/app
COPY --from=copy /usr/src/app/ .
EXPOSE 8080
USER 1000

FROM base AS final
ENV ENV=dev
CMD ["npm", "run", "dev"]
  