services:
  mongodb-auth:
    image: mongo:latest
    container_name: mongodb-auth
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_auth:/data/db
    networks:
      - ecom_network 
    deploy:
      replicas: 1 

  mongodb-product:
    image: mongo:latest
    container_name: mongodb-product
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_product:/data/db
    networks:
      - ecom_network 
    deploy:
      replicas: 1 

  mongodb-order:
    image: mongo:latest
    container_name: mongodb-order
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data_order:/data/db
    networks:
      - ecom_network 
    deploy:
      replicas: 1 

  auth-service:
    image: registry.cecoule.fr:5000/auth-prod:v1
    container_name: auth-service
    restart: always
    env_file:
      - ./services/auth-service/.env.production
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=${MONGODB_URI} 
    depends_on:
      - mongodb-auth
    networks:
      - ecom_network

  product-service:
    image: registry.cecoule.fr:5000/product-prod:v1
    container_name: product-service
    restart: always
    env_file:
      - ./services/product-service/.env.production
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGODB_URI}
    depends_on:
      - mongodb-product
    networks:
      - ecom_network

  order-service:
    image: registry.cecoule.fr:5000/order-prod:v1
    container_name: order-service
    restart: always
    env_file:
      - ./services/order-service/.env.production
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=${MONGODB_URI}
    depends_on:
      - mongodb-order
    networks:
      - ecom_network

  frontend:
    image: registry.cecoule.fr:5000/frontend-prod:v1
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env.production
    ports:
      - "8080:8080"
    networks:
      - ecom_network

networks:
  ecom_network:
    driver: overlay

volumes:
  mongodb_data_auth:
    driver: local
  mongodb_data_product:
    driver: local
  mongodb_data_order:
    driver: local
